# Generated by Django 4.0.3 on 2022-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('boss_name', models.CharField(choices=[('0', 'Director'), ('1', 'Group Leader'), ('2', 'Middle manager'), ('3', 'Manager'), ('4', 'Employee')], default=' ', max_length=15, verbose_name='Post')),
                ('subordinate_level', models.CharField(choices=[('0', 'You BOSS'), ('1', 'Director'), ('2', 'Group Leader'), ('3', 'Middle manager'), ('4', 'Manager')], max_length=15, primary_key=True, serialize=False, verbose_name='Subordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_of_employment', models.DateField()),
                ('Salary_amount', models.CharField(max_length=64)),
                ('salary_paid', models.CharField(max_length=64)),
                ('post', models.CharField(choices=[('0', 'Director'), ('1', 'Group Leader'), ('2', 'Middle manager'), ('3', 'Manager'), ('4', 'Employee')], max_length=15, primary_key=True, serialize=False, verbose_name='Post')),
            ],
        ),
    ]
