# Generated by Django 4.0.3 on 2022-03-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('post', models.CharField(max_length=64)),
                ('date_of_employment', models.PositiveIntegerField()),
                ('Salary_amount', models.CharField(max_length=64)),
                ('salary_paid', models.CharField(max_length=64)),
            ],
        ),
    ]
