# Generated by Django 4.0.3 on 2022-03-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='boss_name',
            field=models.CharField(choices=[('0', 'You BOSS'), ('1', 'Director'), ('2', 'Group Leader'), ('3', 'Middle manager'), ('4', 'Manager')], default=' ', max_length=15, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='boss',
            name='subordinate_level',
            field=models.CharField(choices=[('0', 'Director'), ('1', 'Group Leader'), ('2', 'Middle manager'), ('3', 'Manager'), ('4', 'Employee')], max_length=15, primary_key=True, serialize=False, verbose_name='Subordinate'),
        ),
    ]
